[package]
name = "ferris" # the name of the package
version = "0.9.0"    # the current version, obeying semver
authors = ["bpg@pdx.edu", "kououken@gmail.com", "rbartz@pdx.edu"]
build = "build.rs"


[dependencies]
ggez = "0.4"
rand = "0.4"
