[package]
name = "ferris" # the name of the package
version = "0.9.1"    # the current version, obeying semver
authors = ["bpg@pdx.edu", "kououken@gmail.com", "rbartz.pdx.edu"]
build = "build.rs"

[dependencies]
ggez = "0.4"
lazy_static = "*"
rand = "0.4"
